config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root  'static_pages#home'
  get   'about'   => 'static_pages#about'
  get   'contact' => 'static_pages#contact'
  get   'signup'  =>  'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
	def home
	end

	def about
	end

	def contact
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Multitude - Christian Retreats"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-bottom navbar-inverse">
  <div class="container">
	  <small>
	    <%= link_to "Multitude", root_path %> is a free service for Christians to find retreats.
	  </small>
	  <nav class="navbar-right">
	    <ul class="nav navbar-nav">
	      <li><%= link_to "About",   about_path %></li>
	      <li><%= link_to "Contact", contact_path %></li>
	    </ul>
	  </nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header> 
	<% if current_page?(controller: "static_pages", action: 'home') %>
		<div id="home_header" class="container-fluid">
		<% logo = image_tag('logo-home.png') %>	
	<% else %>
		<div id="header" class="container-fluid">
		<% logo = image_tag('logo.png') %>	
	<% end %>

		<nav class="navbar navbar-static-top" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">

			<!-- hidden nav button toggle for screen readers -->
			<div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	      </button>
	    </div>

	    <!-- navigation grouped with logo for mobile -->
	    <div class="collapse navbar-collapse clearfix">
	    	<%= link_to logo, root_path, class: "navbar-brand pull-left", id: "logo" %>	
	    	<ul class="nav navbar-nav pull-right">
	    		<li><%= link_to "Sign Up", signup_path %></li>
	    		<li><a href="#">Log In</a></li>
	    		<li><%= link_to "Help", contact_path %></li>
	    		<li><button type="button" class="btn btn-primary navbar-btn">List Your Retreat</button></li>
	    	</ul>
	    </div>
	  </nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield :page_title) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 
	  																					'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>

app/views/retreats/show.html.erb
<body class="phonebook">
  <article itemscope itemtype="http://schema.org/Organization">
    <h1 itemprop="name">Google, Inc.</h1>
    <a class="simple" title="Find Google, Inc. on Google Maps" href="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=1600+amphitheatre+parkway+mountain+view+ca&amp;sll=37.0625,-95.677068&amp;sspn=47.569986,93.076172&amp;ie=UTF8&amp;hq=&amp;hnear=1600+Amphitheatre+Pkwy,+Mountain+View,+Santa+Clara,+California+94043&amp;z=16&amp;iwloc=r0">
      <img src="freedo_Glossy_Globe.png" alt="[globe]" width="100" height="100" />
    </a>
    <p itemprop="address" itemscope
       itemtype="http://data-vocabulary.org/Address">
      <span itemprop="street-address">1600 Amphitheatre Parkway</span><br>
      <span itemprop="locality">Mountain View</span>,
      <span itemprop="region">CA</span>
      <span itemprop="postal-code">94043</span>
      <span itemprop="country-name">USA</span>
    </p>
    <p itemprop="tel">650-253-0000</p>
    <p><a itemprop="url" href="http://www.google.com/">Google.com</a></p>
    <span itemprop="geo" itemscope itemtype="http://data-vocabulary.org/Geo">
      <meta itemprop="latitude" content="37.4149" />
      <meta itemprop="longitude" content="-122.078" />
    </span>

  </article>

app/views/static_pages/about.html.erb
<% provide(:page_title, 'About') %>

	<div itemscope itemtype="http://schema.org/Organization">
		<span itemprop="description">Multitude is a Christian organization that makes it easy for christians to find and book retreats.</span>
	</div>

	<a href="<%= 'contact' %>">Contact us</a> for more information.

app/views/static_pages/contact.html.erb
<% provide(:page_title, 'Help') %>


	<h1>Contact Customer Support</h1>

	<div itemscope itemtype="http://schema.org/Organization">
	  <span itemprop="name">Multitude Inc.</span>

	  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
	    Address:
	      <span itemprop="streetAddress">635 Fake Avenue</span>
	      <span itemprop="addressLocality">Sunnyvale, CA</span>
	      <span itemprop="postalCode">94087</span> 
	  </div>
	    Tel:<span itemprop="telephone">(999) 329 3094</span>
	    E-mail: <span itemprop="email">support@multitude.io</span>
	</div>

app/views/static_pages/home.html.erb
<% provide(:page_title, 'Home') %>
</div>
<div class="jumbotron">
  <div class="container text-center">
	  <h1>WELCOME. REST AWAITS.</h1>
	  <p>Find the perfect place for your church, group or personal retreat.</p>
  	<div class="container">
  		<div class="row">	
		    <div class="col-xs-4 center-block">
	        <div class="input">
	            <input type="text" class="form-control" placeholder="Where"/>
	        </div>
	     	</div>
	     	<div class="col-xs-2 center-block">
	        <div class="input">
	            <input type="date" class="form-control" placeholder="Arriving"/>
	        </div>
	     	</div>
	     	<div class="col-xs-2 center-block">
	        <div class="input">
	            <input type="date" class="form-control" placeholder="Leaving"/>
	        </div>
	     	</div>
	        <span class="col-xs-1 center-block"><button class="btn btn-default btn-md" type="button">Search</button>
	        </span>
	    </div>
    </div><!-- /.row -->
  </div>
</div>

<div itemscope itemtype="http://schema.org/Organization">
	<span itemprop="description">Multitude makes it easy for christians to find and book retreats.</span>
</div>

<a href="<%= 'contact' %>">Contact us</a> for more information.
<div class="container">

app/views/users/new.html.erb
<% provide(:page_title, 'Sign Up') %>
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>